server:
  port: 8081
spring:
    datasource:
        name: test
        url: jdbc:mysql://172.16.250.145:3306/sckj?characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ocean.pojo
jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#上传位置
uploadDir: /Users/hww/Documents/IMAGE/
localurl: https://localhost/
