
server:
  port: 8081

spring:
    datasource:
        name: test
        url: jdbc:mysql://172.16.250.138:3306/sckj
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ocean.pojo

