server:
  port: 8081
spring:
    datasource:
        name: test
        url: jdbc:mysql://47.100.167.119:3306/sckj?characterEncoding=utf-8
        username: root
        password: ShouCha123#
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
      cache: false #禁止thymeleaf缓存（建议：开发环境设置为false，生成环境设置为true）
    devtools:
      restart:
        additional-paths: src/main/java
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.sckj.model
jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#上传位置
uploadDir: D:/19tea/image/
#uploadDir: /Users/hww/Documents/IMAGE/
localurl: https://localhost/

weixin4j:
  #微信开发配置
  config:
    #开发者第三方用户唯一凭证
    appid:
    #开发者第三方用户唯一凭证密钥
    secret:
    #公众号原始ID
    originalid:
    #消息加密方式 0:明文模式(默认), 1:兼容模式, 2:安全模式(推荐)
    encodingtype: 0
    #消息加密密钥(43位字符组成A-Za-z0-9)
    encodingaeskey: 0123456789abcedfghijklmnopqrstuvwxyzZXCVBNM
    #网页安全授权URL
    oauthUrl:
  #微信支付配置
  pay:
    #微信支付_商户ID，例如10000000001
    partnerId:
    #微信支付_商户密钥，由商户设置32位字符
    partnerKey:
    #微信支付_通知URL，异步接收微信支付结果的URL
    notifyUrl:
    #证书路径(pk12格式)，例如：/opt/cert/10000000001.pk12
    certPath:
    #证书密钥,默认为商户ID，例如：10000000001
    certSecret:
