package com.sckj.pojo;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import javax.persistence.Entity;
import javax.persistence.Table;

//@Entity
//@Table(name = "sckj_user_list")
//@JsonSerialize(include= JsonSerialize.Inclusion.NON_NULL)
public class UserCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_user_cart.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_user_cart.userid
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_user_cart.productid
     *
     * @mbg.generated
     */
    private String productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_user_cart.specificationid
     *
     * @mbg.generated
     */
    private String specificationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_user_cart.product_type
     *
     * @mbg.generated
     */
    private String productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_user_cart.num
     *
     * @mbg.generated
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_user_cart.cart_type
     *
     * @mbg.generated
     */
    private String cartType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_user_cart.Status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_user_cart.id
     *
     * @return the value of sckj_user_cart.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_user_cart.id
     *
     * @param id the value for sckj_user_cart.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_user_cart.userid
     *
     * @return the value of sckj_user_cart.userid
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_user_cart.userid
     *
     * @param userid the value for sckj_user_cart.userid
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_user_cart.productid
     *
     * @return the value of sckj_user_cart.productid
     *
     * @mbg.generated
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_user_cart.productid
     *
     * @param productid the value for sckj_user_cart.productid
     *
     * @mbg.generated
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_user_cart.specificationid
     *
     * @return the value of sckj_user_cart.specificationid
     *
     * @mbg.generated
     */
    public String getSpecificationid() {
        return specificationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_user_cart.specificationid
     *
     * @param specificationid the value for sckj_user_cart.specificationid
     *
     * @mbg.generated
     */
    public void setSpecificationid(String specificationid) {
        this.specificationid = specificationid == null ? null : specificationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_user_cart.product_type
     *
     * @return the value of sckj_user_cart.product_type
     *
     * @mbg.generated
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_user_cart.product_type
     *
     * @param productType the value for sckj_user_cart.product_type
     *
     * @mbg.generated
     */
    public void setProductType(String productType) {
        this.productType = productType == null ? null : productType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_user_cart.num
     *
     * @return the value of sckj_user_cart.num
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_user_cart.num
     *
     * @param num the value for sckj_user_cart.num
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_user_cart.cart_type
     *
     * @return the value of sckj_user_cart.cart_type
     *
     * @mbg.generated
     */
    public String getCartType() {
        return cartType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_user_cart.cart_type
     *
     * @param cartType the value for sckj_user_cart.cart_type
     *
     * @mbg.generated
     */
    public void setCartType(String cartType) {
        this.cartType = cartType == null ? null : cartType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_user_cart.Status
     *
     * @return the value of sckj_user_cart.Status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_user_cart.Status
     *
     * @param status the value for sckj_user_cart.Status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}