package com.sckj.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class XCXSTUserList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.Tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.openid_app
     *
     * @mbggenerated
     */
    private String openidApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.unionid
     *
     * @mbggenerated
     */
    private String unionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.pwd
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.pay_pwd
     *
     * @mbggenerated
     */
    private String payPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.myword
     *
     * @mbggenerated
     */
    private String myword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.professional
     *
     * @mbggenerated
     */
    private String professional;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.user_type
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.scores
     *
     * @mbggenerated
     */
    private BigDecimal scores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.Commission
     *
     * @mbggenerated
     */
    private BigDecimal commission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.Consumption
     *
     * @mbggenerated
     */
    private BigDecimal consumption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.money
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.agent_money
     *
     * @mbggenerated
     */
    private BigDecimal agentMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.idcard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.regtime
     *
     * @mbggenerated
     */
    private Date regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.lastlogintime
     *
     * @mbggenerated
     */
    private Date lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.Status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.rd_session
     *
     * @mbggenerated
     */
    private String rdSession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.session_key
     *
     * @mbggenerated
     */
    private String sessionKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XCXST_user_list.headimg
     *
     * @mbggenerated
     */
    private String headimg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.id
     *
     * @return the value of XCXST_user_list.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.id
     *
     * @param id the value for XCXST_user_list.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.Tel
     *
     * @return the value of XCXST_user_list.Tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.Tel
     *
     * @param tel the value for XCXST_user_list.Tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.openid
     *
     * @return the value of XCXST_user_list.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.openid
     *
     * @param openid the value for XCXST_user_list.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.openid_app
     *
     * @return the value of XCXST_user_list.openid_app
     *
     * @mbggenerated
     */
    public String getOpenidApp() {
        return openidApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.openid_app
     *
     * @param openidApp the value for XCXST_user_list.openid_app
     *
     * @mbggenerated
     */
    public void setOpenidApp(String openidApp) {
        this.openidApp = openidApp == null ? null : openidApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.unionid
     *
     * @return the value of XCXST_user_list.unionid
     *
     * @mbggenerated
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.unionid
     *
     * @param unionid the value for XCXST_user_list.unionid
     *
     * @mbggenerated
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.pwd
     *
     * @return the value of XCXST_user_list.pwd
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.pwd
     *
     * @param pwd the value for XCXST_user_list.pwd
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.pay_pwd
     *
     * @return the value of XCXST_user_list.pay_pwd
     *
     * @mbggenerated
     */
    public String getPayPwd() {
        return payPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.pay_pwd
     *
     * @param payPwd the value for XCXST_user_list.pay_pwd
     *
     * @mbggenerated
     */
    public void setPayPwd(String payPwd) {
        this.payPwd = payPwd == null ? null : payPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.nickname
     *
     * @return the value of XCXST_user_list.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.nickname
     *
     * @param nickname the value for XCXST_user_list.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.myword
     *
     * @return the value of XCXST_user_list.myword
     *
     * @mbggenerated
     */
    public String getMyword() {
        return myword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.myword
     *
     * @param myword the value for XCXST_user_list.myword
     *
     * @mbggenerated
     */
    public void setMyword(String myword) {
        this.myword = myword == null ? null : myword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.birthday
     *
     * @return the value of XCXST_user_list.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.birthday
     *
     * @param birthday the value for XCXST_user_list.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.professional
     *
     * @return the value of XCXST_user_list.professional
     *
     * @mbggenerated
     */
    public String getProfessional() {
        return professional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.professional
     *
     * @param professional the value for XCXST_user_list.professional
     *
     * @mbggenerated
     */
    public void setProfessional(String professional) {
        this.professional = professional == null ? null : professional.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.user_type
     *
     * @return the value of XCXST_user_list.user_type
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.user_type
     *
     * @param userType the value for XCXST_user_list.user_type
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.scores
     *
     * @return the value of XCXST_user_list.scores
     *
     * @mbggenerated
     */
    public BigDecimal getScores() {
        return scores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.scores
     *
     * @param scores the value for XCXST_user_list.scores
     *
     * @mbggenerated
     */
    public void setScores(BigDecimal scores) {
        this.scores = scores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.Commission
     *
     * @return the value of XCXST_user_list.Commission
     *
     * @mbggenerated
     */
    public BigDecimal getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.Commission
     *
     * @param commission the value for XCXST_user_list.Commission
     *
     * @mbggenerated
     */
    public void setCommission(BigDecimal commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.Consumption
     *
     * @return the value of XCXST_user_list.Consumption
     *
     * @mbggenerated
     */
    public BigDecimal getConsumption() {
        return consumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.Consumption
     *
     * @param consumption the value for XCXST_user_list.Consumption
     *
     * @mbggenerated
     */
    public void setConsumption(BigDecimal consumption) {
        this.consumption = consumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.money
     *
     * @return the value of XCXST_user_list.money
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.money
     *
     * @param money the value for XCXST_user_list.money
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.agent_money
     *
     * @return the value of XCXST_user_list.agent_money
     *
     * @mbggenerated
     */
    public BigDecimal getAgentMoney() {
        return agentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.agent_money
     *
     * @param agentMoney the value for XCXST_user_list.agent_money
     *
     * @mbggenerated
     */
    public void setAgentMoney(BigDecimal agentMoney) {
        this.agentMoney = agentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.idcard
     *
     * @return the value of XCXST_user_list.idcard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.idcard
     *
     * @param idcard the value for XCXST_user_list.idcard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.sex
     *
     * @return the value of XCXST_user_list.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.sex
     *
     * @param sex the value for XCXST_user_list.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.province
     *
     * @return the value of XCXST_user_list.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.province
     *
     * @param province the value for XCXST_user_list.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.city
     *
     * @return the value of XCXST_user_list.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.city
     *
     * @param city the value for XCXST_user_list.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.area
     *
     * @return the value of XCXST_user_list.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.area
     *
     * @param area the value for XCXST_user_list.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.address
     *
     * @return the value of XCXST_user_list.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.address
     *
     * @param address the value for XCXST_user_list.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.regtime
     *
     * @return the value of XCXST_user_list.regtime
     *
     * @mbggenerated
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.regtime
     *
     * @param regtime the value for XCXST_user_list.regtime
     *
     * @mbggenerated
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.lastlogintime
     *
     * @return the value of XCXST_user_list.lastlogintime
     *
     * @mbggenerated
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.lastlogintime
     *
     * @param lastlogintime the value for XCXST_user_list.lastlogintime
     *
     * @mbggenerated
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.Status
     *
     * @return the value of XCXST_user_list.Status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.Status
     *
     * @param status the value for XCXST_user_list.Status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.token
     *
     * @return the value of XCXST_user_list.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.token
     *
     * @param token the value for XCXST_user_list.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.rd_session
     *
     * @return the value of XCXST_user_list.rd_session
     *
     * @mbggenerated
     */
    public String getRdSession() {
        return rdSession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.rd_session
     *
     * @param rdSession the value for XCXST_user_list.rd_session
     *
     * @mbggenerated
     */
    public void setRdSession(String rdSession) {
        this.rdSession = rdSession == null ? null : rdSession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.session_key
     *
     * @return the value of XCXST_user_list.session_key
     *
     * @mbggenerated
     */
    public String getSessionKey() {
        return sessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.session_key
     *
     * @param sessionKey the value for XCXST_user_list.session_key
     *
     * @mbggenerated
     */
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey == null ? null : sessionKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XCXST_user_list.headimg
     *
     * @return the value of XCXST_user_list.headimg
     *
     * @mbggenerated
     */
    public String getHeadimg() {
        return headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XCXST_user_list.headimg
     *
     * @param headimg the value for XCXST_user_list.headimg
     *
     * @mbggenerated
     */
    public void setHeadimg(String headimg) {
        this.headimg = headimg == null ? null : headimg.trim();
    }
}