package com.sckj.model.test;

public class ProductOrderWithBLOBs extends ProductOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.refundreason
     *
     * @mbg.generated
     */
    private String refundreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.refund_remark
     *
     * @mbg.generated
     */
    private String refundRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.refundreason
     *
     * @return the value of sckj_product_order.refundreason
     *
     * @mbg.generated
     */
    public String getRefundreason() {
        return refundreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.refundreason
     *
     * @param refundreason the value for sckj_product_order.refundreason
     *
     * @mbg.generated
     */
    public void setRefundreason(String refundreason) {
        this.refundreason = refundreason == null ? null : refundreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.refund_remark
     *
     * @return the value of sckj_product_order.refund_remark
     *
     * @mbg.generated
     */
    public String getRefundRemark() {
        return refundRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.refund_remark
     *
     * @param refundRemark the value for sckj_product_order.refund_remark
     *
     * @mbg.generated
     */
    public void setRefundRemark(String refundRemark) {
        this.refundRemark = refundRemark == null ? null : refundRemark.trim();
    }
}