package com.sckj.model.test;

import java.math.BigDecimal;
import java.util.Date;

public class ProductOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.buyuser_id
     *
     * @mbg.generated
     */
    private String buyuserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.buyuser_tel
     *
     * @mbg.generated
     */
    private String buyuserTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.payuser
     *
     * @mbg.generated
     */
    private String payuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.express_price
     *
     * @mbg.generated
     */
    private BigDecimal expressPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.product_price
     *
     * @mbg.generated
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.vip_price
     *
     * @mbg.generated
     */
    private BigDecimal vipPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.coupon_price
     *
     * @mbg.generated
     */
    private BigDecimal couponPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.total_price
     *
     * @mbg.generated
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.pay_method
     *
     * @mbg.generated
     */
    private String payMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.isapp
     *
     * @mbg.generated
     */
    private String isapp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.order_status
     *
     * @mbg.generated
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.payremind
     *
     * @mbg.generated
     */
    private String payremind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.paytime
     *
     * @mbg.generated
     */
    private Date paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.signer
     *
     * @mbg.generated
     */
    private String signer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.signer_tel
     *
     * @mbg.generated
     */
    private String signerTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.user_remark
     *
     * @mbg.generated
     */
    private String userRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.shareuid
     *
     * @mbg.generated
     */
    private String shareuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.refundstatus
     *
     * @mbg.generated
     */
    private String refundstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.refund_id
     *
     * @mbg.generated
     */
    private String refundId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.refund_express
     *
     * @mbg.generated
     */
    private String refundExpress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.refund_time
     *
     * @mbg.generated
     */
    private Date refundTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.confirm_time
     *
     * @mbg.generated
     */
    private Date confirmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.prepay_id
     *
     * @mbg.generated
     */
    private String prepayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.Status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.express_name
     *
     * @mbg.generated
     */
    private String expressName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.express_code
     *
     * @mbg.generated
     */
    private String expressCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.express_orderid
     *
     * @mbg.generated
     */
    private String expressOrderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.m_refundtime
     *
     * @mbg.generated
     */
    private Date mRefundtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.is_syn_gjp
     *
     * @mbg.generated
     */
    private String isSynGjp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sckj_product_order.syn_gjp_time
     *
     * @mbg.generated
     */
    private Date synGjpTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.id
     *
     * @return the value of sckj_product_order.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.id
     *
     * @param id the value for sckj_product_order.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.buyuser_id
     *
     * @return the value of sckj_product_order.buyuser_id
     *
     * @mbg.generated
     */
    public String getBuyuserId() {
        return buyuserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.buyuser_id
     *
     * @param buyuserId the value for sckj_product_order.buyuser_id
     *
     * @mbg.generated
     */
    public void setBuyuserId(String buyuserId) {
        this.buyuserId = buyuserId == null ? null : buyuserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.buyuser_tel
     *
     * @return the value of sckj_product_order.buyuser_tel
     *
     * @mbg.generated
     */
    public String getBuyuserTel() {
        return buyuserTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.buyuser_tel
     *
     * @param buyuserTel the value for sckj_product_order.buyuser_tel
     *
     * @mbg.generated
     */
    public void setBuyuserTel(String buyuserTel) {
        this.buyuserTel = buyuserTel == null ? null : buyuserTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.payuser
     *
     * @return the value of sckj_product_order.payuser
     *
     * @mbg.generated
     */
    public String getPayuser() {
        return payuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.payuser
     *
     * @param payuser the value for sckj_product_order.payuser
     *
     * @mbg.generated
     */
    public void setPayuser(String payuser) {
        this.payuser = payuser == null ? null : payuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.express_price
     *
     * @return the value of sckj_product_order.express_price
     *
     * @mbg.generated
     */
    public BigDecimal getExpressPrice() {
        return expressPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.express_price
     *
     * @param expressPrice the value for sckj_product_order.express_price
     *
     * @mbg.generated
     */
    public void setExpressPrice(BigDecimal expressPrice) {
        this.expressPrice = expressPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.product_price
     *
     * @return the value of sckj_product_order.product_price
     *
     * @mbg.generated
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.product_price
     *
     * @param productPrice the value for sckj_product_order.product_price
     *
     * @mbg.generated
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.vip_price
     *
     * @return the value of sckj_product_order.vip_price
     *
     * @mbg.generated
     */
    public BigDecimal getVipPrice() {
        return vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.vip_price
     *
     * @param vipPrice the value for sckj_product_order.vip_price
     *
     * @mbg.generated
     */
    public void setVipPrice(BigDecimal vipPrice) {
        this.vipPrice = vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.coupon_price
     *
     * @return the value of sckj_product_order.coupon_price
     *
     * @mbg.generated
     */
    public BigDecimal getCouponPrice() {
        return couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.coupon_price
     *
     * @param couponPrice the value for sckj_product_order.coupon_price
     *
     * @mbg.generated
     */
    public void setCouponPrice(BigDecimal couponPrice) {
        this.couponPrice = couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.total_price
     *
     * @return the value of sckj_product_order.total_price
     *
     * @mbg.generated
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.total_price
     *
     * @param totalPrice the value for sckj_product_order.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.pay_method
     *
     * @return the value of sckj_product_order.pay_method
     *
     * @mbg.generated
     */
    public String getPayMethod() {
        return payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.pay_method
     *
     * @param payMethod the value for sckj_product_order.pay_method
     *
     * @mbg.generated
     */
    public void setPayMethod(String payMethod) {
        this.payMethod = payMethod == null ? null : payMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.isapp
     *
     * @return the value of sckj_product_order.isapp
     *
     * @mbg.generated
     */
    public String getIsapp() {
        return isapp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.isapp
     *
     * @param isapp the value for sckj_product_order.isapp
     *
     * @mbg.generated
     */
    public void setIsapp(String isapp) {
        this.isapp = isapp == null ? null : isapp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.order_status
     *
     * @return the value of sckj_product_order.order_status
     *
     * @mbg.generated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.order_status
     *
     * @param orderStatus the value for sckj_product_order.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.createtime
     *
     * @return the value of sckj_product_order.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.createtime
     *
     * @param createtime the value for sckj_product_order.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.payremind
     *
     * @return the value of sckj_product_order.payremind
     *
     * @mbg.generated
     */
    public String getPayremind() {
        return payremind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.payremind
     *
     * @param payremind the value for sckj_product_order.payremind
     *
     * @mbg.generated
     */
    public void setPayremind(String payremind) {
        this.payremind = payremind == null ? null : payremind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.paytime
     *
     * @return the value of sckj_product_order.paytime
     *
     * @mbg.generated
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.paytime
     *
     * @param paytime the value for sckj_product_order.paytime
     *
     * @mbg.generated
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.remark
     *
     * @return the value of sckj_product_order.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.remark
     *
     * @param remark the value for sckj_product_order.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.signer
     *
     * @return the value of sckj_product_order.signer
     *
     * @mbg.generated
     */
    public String getSigner() {
        return signer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.signer
     *
     * @param signer the value for sckj_product_order.signer
     *
     * @mbg.generated
     */
    public void setSigner(String signer) {
        this.signer = signer == null ? null : signer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.signer_tel
     *
     * @return the value of sckj_product_order.signer_tel
     *
     * @mbg.generated
     */
    public String getSignerTel() {
        return signerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.signer_tel
     *
     * @param signerTel the value for sckj_product_order.signer_tel
     *
     * @mbg.generated
     */
    public void setSignerTel(String signerTel) {
        this.signerTel = signerTel == null ? null : signerTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.province
     *
     * @return the value of sckj_product_order.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.province
     *
     * @param province the value for sckj_product_order.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.city
     *
     * @return the value of sckj_product_order.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.city
     *
     * @param city the value for sckj_product_order.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.area
     *
     * @return the value of sckj_product_order.area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.area
     *
     * @param area the value for sckj_product_order.area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.address
     *
     * @return the value of sckj_product_order.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.address
     *
     * @param address the value for sckj_product_order.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.user_remark
     *
     * @return the value of sckj_product_order.user_remark
     *
     * @mbg.generated
     */
    public String getUserRemark() {
        return userRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.user_remark
     *
     * @param userRemark the value for sckj_product_order.user_remark
     *
     * @mbg.generated
     */
    public void setUserRemark(String userRemark) {
        this.userRemark = userRemark == null ? null : userRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.shareuid
     *
     * @return the value of sckj_product_order.shareuid
     *
     * @mbg.generated
     */
    public String getShareuid() {
        return shareuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.shareuid
     *
     * @param shareuid the value for sckj_product_order.shareuid
     *
     * @mbg.generated
     */
    public void setShareuid(String shareuid) {
        this.shareuid = shareuid == null ? null : shareuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.refundstatus
     *
     * @return the value of sckj_product_order.refundstatus
     *
     * @mbg.generated
     */
    public String getRefundstatus() {
        return refundstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.refundstatus
     *
     * @param refundstatus the value for sckj_product_order.refundstatus
     *
     * @mbg.generated
     */
    public void setRefundstatus(String refundstatus) {
        this.refundstatus = refundstatus == null ? null : refundstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.refund_id
     *
     * @return the value of sckj_product_order.refund_id
     *
     * @mbg.generated
     */
    public String getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.refund_id
     *
     * @param refundId the value for sckj_product_order.refund_id
     *
     * @mbg.generated
     */
    public void setRefundId(String refundId) {
        this.refundId = refundId == null ? null : refundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.refund_express
     *
     * @return the value of sckj_product_order.refund_express
     *
     * @mbg.generated
     */
    public String getRefundExpress() {
        return refundExpress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.refund_express
     *
     * @param refundExpress the value for sckj_product_order.refund_express
     *
     * @mbg.generated
     */
    public void setRefundExpress(String refundExpress) {
        this.refundExpress = refundExpress == null ? null : refundExpress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.refund_time
     *
     * @return the value of sckj_product_order.refund_time
     *
     * @mbg.generated
     */
    public Date getRefundTime() {
        return refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.refund_time
     *
     * @param refundTime the value for sckj_product_order.refund_time
     *
     * @mbg.generated
     */
    public void setRefundTime(Date refundTime) {
        this.refundTime = refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.confirm_time
     *
     * @return the value of sckj_product_order.confirm_time
     *
     * @mbg.generated
     */
    public Date getConfirmTime() {
        return confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.confirm_time
     *
     * @param confirmTime the value for sckj_product_order.confirm_time
     *
     * @mbg.generated
     */
    public void setConfirmTime(Date confirmTime) {
        this.confirmTime = confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.prepay_id
     *
     * @return the value of sckj_product_order.prepay_id
     *
     * @mbg.generated
     */
    public String getPrepayId() {
        return prepayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.prepay_id
     *
     * @param prepayId the value for sckj_product_order.prepay_id
     *
     * @mbg.generated
     */
    public void setPrepayId(String prepayId) {
        this.prepayId = prepayId == null ? null : prepayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.Status
     *
     * @return the value of sckj_product_order.Status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.Status
     *
     * @param status the value for sckj_product_order.Status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.express_name
     *
     * @return the value of sckj_product_order.express_name
     *
     * @mbg.generated
     */
    public String getExpressName() {
        return expressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.express_name
     *
     * @param expressName the value for sckj_product_order.express_name
     *
     * @mbg.generated
     */
    public void setExpressName(String expressName) {
        this.expressName = expressName == null ? null : expressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.express_code
     *
     * @return the value of sckj_product_order.express_code
     *
     * @mbg.generated
     */
    public String getExpressCode() {
        return expressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.express_code
     *
     * @param expressCode the value for sckj_product_order.express_code
     *
     * @mbg.generated
     */
    public void setExpressCode(String expressCode) {
        this.expressCode = expressCode == null ? null : expressCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.express_orderid
     *
     * @return the value of sckj_product_order.express_orderid
     *
     * @mbg.generated
     */
    public String getExpressOrderid() {
        return expressOrderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.express_orderid
     *
     * @param expressOrderid the value for sckj_product_order.express_orderid
     *
     * @mbg.generated
     */
    public void setExpressOrderid(String expressOrderid) {
        this.expressOrderid = expressOrderid == null ? null : expressOrderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.m_refundtime
     *
     * @return the value of sckj_product_order.m_refundtime
     *
     * @mbg.generated
     */
    public Date getmRefundtime() {
        return mRefundtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.m_refundtime
     *
     * @param mRefundtime the value for sckj_product_order.m_refundtime
     *
     * @mbg.generated
     */
    public void setmRefundtime(Date mRefundtime) {
        this.mRefundtime = mRefundtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.is_syn_gjp
     *
     * @return the value of sckj_product_order.is_syn_gjp
     *
     * @mbg.generated
     */
    public String getIsSynGjp() {
        return isSynGjp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.is_syn_gjp
     *
     * @param isSynGjp the value for sckj_product_order.is_syn_gjp
     *
     * @mbg.generated
     */
    public void setIsSynGjp(String isSynGjp) {
        this.isSynGjp = isSynGjp == null ? null : isSynGjp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sckj_product_order.syn_gjp_time
     *
     * @return the value of sckj_product_order.syn_gjp_time
     *
     * @mbg.generated
     */
    public Date getSynGjpTime() {
        return synGjpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sckj_product_order.syn_gjp_time
     *
     * @param synGjpTime the value for sckj_product_order.syn_gjp_time
     *
     * @mbg.generated
     */
    public void setSynGjpTime(Date synGjpTime) {
        this.synGjpTime = synGjpTime;
    }
}