package com.sckj.repository.mybatis;

import com.sckj.model.dto.SckjUserListDTO;
import com.sckj.model.UserList;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.util.List;
import java.util.Map;

public interface UserListDAO {

    Page<SckjUserListDTO> findUserListPage(UserList userList, Pageable page);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_list
     *
     * @mbg.generated
     */
    int insert(UserList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_list
     *
     * @mbg.generated
     */
    int insertSelective(UserList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_list
     *
     * @mbg.generated
     */
    UserList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(UserList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserList record);

    List<SckjUserListDTO> selectUser();

    List<SckjUserListDTO> getUserList(Map<String,Object> map);
}