package com.sckj.dao;

import com.sckj.pojo.ProductListWithBLOBs;

public interface ProductListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_product_list
     *
     * @mbg.generated
     */
    int insert(ProductListWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_product_list
     *
     * @mbg.generated
     */
    int insertSelective(ProductListWithBLOBs record);
}