package com.sckj.dao;

import com.sckj.dto.ProductListDTO;
import com.sckj.pojo.ProductListWithBLOBs;

import java.util.List;
import java.util.Map;

public interface ProductListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_product_list
     *
     * @mbg.generated
     */
    int insert(ProductListWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_product_list
     *
     * @mbg.generated
     */
    int insertSelective(ProductListWithBLOBs record);

    int deleteProductByIds(String[] ids);

    List<ProductListDTO> getProductList(Map<String,Object> map);

    ProductListWithBLOBs  getOne(String id);
}