package com.sckj.dao;

import com.sckj.pojo.SckjUserList;

public interface sckjUserListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_list
     *
     * @mbg.generated
     */
    int insert(SckjUserList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_list
     *
     * @mbg.generated
     */
    int insertSelective(SckjUserList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_list
     *
     * @mbg.generated
     */
    SckjUserList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SckjUserList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SckjUserList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SckjUserList record);
}