package com.sckj.dao;

import com.sckj.pojo.UserCart;

public interface UserCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_cart
     *
     * @mbg.generated
     */
    int insert(UserCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_cart
     *
     * @mbg.generated
     */
    int insertSelective(UserCart record);
}