package com.sckj.dao;

import com.sckj.dto.UserCartDTO;
import com.sckj.pojo.UserCart;
import org.apache.ibatis.annotations.Param;

import java.util.List;


public interface UserCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_cart
     *
     * @mbg.generated
     */
    int insert(UserCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_user_cart
     *
     * @mbg.generated
     */
    int insertSelective(UserCart record);

    List<UserCartDTO> getUserCartList(@Param("userid") String userid, @Param("cartType") String cartType);
}