package com.sckj.dao;

import com.sckj.pojo.XCXSTUserList;

public interface XCXSTUserListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XCXST_user_list
     *
     * @mbggenerated
     */
    int insert(XCXSTUserList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XCXST_user_list
     *
     * @mbggenerated
     */
    int insertSelective(XCXSTUserList record);
}