package com.sckj.dao.test;

import com.sckj.model.test.ProductOrder;
import com.sckj.model.test.ProductOrderWithBLOBs;

public interface ProductOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_product_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_product_order
     *
     * @mbg.generated
     */
    int insert(ProductOrderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_product_order
     *
     * @mbg.generated
     */
    int insertSelective(ProductOrderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_product_order
     *
     * @mbg.generated
     */
    ProductOrderWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_product_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductOrderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_product_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ProductOrderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sckj_product_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductOrder record);
}